AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Application

Globals:
  Function:
    Timeout: 20

Parameters:
  Application:
    Type: String
    Default: LAMBA_ENTRY_POINT
  Table:
    Type: String
    Default: dummy_table

Resources:

  # DynamoDb table
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "task_id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "task_id"
          KeyType: "HASH"
      TimeToLiveSpecification:
        AttributeName: record_expiration
        Enabled: true
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TableName: !Ref Table

  # Lambda function which process Kinesis input and starts Step Function
  EntryPointLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Entry Point Lambda that will read Kinesis Events and process them
      FunctionName: EntryPointLambda
      CodeUri: entry-point-lambda/build
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 512
      Environment:
        Variables:
          LAMBDA_TABLE: !Ref Table
          SAM_LOCAL: false
          DYNAMODB_HOST: NOT_DEFINED
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Policies:
        - Statement:
          - Effect: Allow
            Action: dynamodb:PutItem
            Resource: !GetAtt DynamoDB.Arn
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt EntryPointLambaInputStreamConsumer.ConsumerARN
            StartingPosition: LATEST
            BatchSize: 100

  # Kinesis Input Stream Event
  EntryPointLambaInputStream:
    Type: "AWS::Kinesis::Stream"
    Properties:
      Name : "EntryPointLambaInputStream"
      ShardCount: 1

  EntryPointLambaInputStreamConsumer:
    Type: "AWS::Kinesis::StreamConsumer"
    Properties:
      StreamARN: !GetAtt EntryPointLambaInputStream.Arn
      ConsumerName: "EntryPointLambaInputStreamConsumer"
