export const status = {
    SCHEDULED: 'SCHEDULED',
    STATE_MACHINE_START_FAILED: 'STATE_MACHINE_START_FAILED',
    MISSING_ATTRIBUTES: 'MISSING_ATTRIBUTES',
    INVALID_PAYLOAD: 'INVALID_PAYLOAD'

};
